# Generated by Django 3.2 on 2020-09-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('critics_consensus', models.TextField(blank=True, verbose_name='Consensus')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Average')),
                ('poster', models.ImageField(blank=True, upload_to='movie/images/', verbose_name='Poster')),
                ('amount_reviews', models.PositiveIntegerField(blank=True, verbose_name='Amount_reviews')),
                ('approval_percentage', models.PositiveIntegerField(blank=True, verbose_name='Percentage')),
            ],
        ),
    ]
