# Generated by Django 3.2 on 2020-09-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amount_reviews',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount_reviews'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='approval_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='critics_consensus',
            field=models.TextField(blank=True, null=True, verbose_name='Consensus'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
