# Generated by Django 3.2 on 2020-09-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_average_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amount_reviews',
            field=models.PositiveIntegerField(verbose_name='Amount_reviews'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='approval_percentage',
            field=models.PositiveIntegerField(verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average_grade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Average'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='critics_consensus',
            field=models.TextField(verbose_name='Consensus'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie/images/', verbose_name='Poster'),
        ),
    ]
