# Generated by Django 3.2 on 2020-09-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200916_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Average'),
        ),
    ]
