# Generated by Django 3.2 on 2020-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_average_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_grade',
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.CharField(blank=True, max_length=255, verbose_name='date'),
        ),
    ]
