# Generated by Django 3.2 on 2020-09-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200916_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, verbose_name='date'),
        ),
    ]
