# Generated by Django 3.2 on 2020-09-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
