# Generated by Django 3.2 on 2020-09-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200921_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieyears',
            old_name='movieyear',
            new_name='year',
        ),
    ]
