# Generated by Django 3.2 on 2020-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_rename_movieyear_movieyears_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MovieYears',
        ),
    ]
