# Generated by Django 3.2 on 2020-09-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20200921_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default=1, upload_to='movie/images/', verbose_name='Poster'),
            preserve_default=False,
        ),
    ]
