# Generated by Django 3.2 on 2020-09-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20200921_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie/images/', verbose_name='Poster'),
        ),
    ]
