# Generated by Django 3.2 on 2020-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbranking',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='imdbranking'),
            preserve_default=False,
        ),
    ]
